### ISSUE TITLE
Play local files

### ISSUE THREAD

**Issue by jsantell** [jsantell/dancer.js#12]
Play local files with drag & drop interface on demo

**Comment by billwoo** [comment]
To evaluate the usefulness of this interesting tool, I need a way to specify a local music to play. thanks, Bill

**Comment by jsantell** [comment]
Gotcha -- will take a look at incorporating FileReader into interface

**Comment by comster** [comment]
any progress on this?  I'm looking to use dancer with an existing audio source.

**Comment by jsantell** [comment]
Same deal with #13 -- once external audio sources can be leveraged, can use FileReader to pass data to that audio source as dancer leverages -- will update with progress :)

**Comment by jsantell** [comment]
@billwoo, @comster: audio elements may now be used as the source for dancer's audio and may be controlled with an audio element as well. With this, you can use a file reader to load audio into an audio element. Check out the `./examples/audio_element/` demo for an example. Thanks!

**Comment by comster** [comment]
I saw your first commit to the audio_element branch :) and hacked it to
work with aurora.  The audio api is slightly different than the audio
element I think.  I'll pull the latest and try to put together an example
and maybe submit a patch if it makes sense.

Great work, Thanks!

**Comment by jsantell** [comment]
The mozilla implementation looks doable, as it just sits on top of an audio element, but Aurora's webkit implementation is all within the Audio Context (Dancer was like that previously, just pushing a buffer, rather than using an audio element), if you get something working, would love to use it!

**Comment by comster** [comment]
My hack worked in Chrome at least, although dirty.  I'm think I'm just
passing through the existing buffer to connect listeners to.  I'll try to
clean it up for posting.

**Comment by comster** [comment]
Hey, I pulled the latest and tried to work in my changes.

I've got a branch for it here: https://github.com/comster/dancer.js/tree/audioapi

I need to add the moz adapter still, but it seems to work in Chrome. I've made an example folder to test using local files and aurora, but unfortunately it doesn't work when running the html via file:// and needs to be run from http://

**Comment by jsantell** [comment]
Excellent, I think I see what's going on here -- this is for getting it working with Aurora? Is it also for using local files (which _may_ not be the responsibility of Dancer, since ultimately it just goes in an audio element)

**Comment by comster** [comment]
Ya.  Aurora has both loadFile and loadURL.  Unfortunately I wasn't able to get either working when running the example via file:// but it's a neat library supporting many codecs. 

You can see the example here: https://github.com/comster/dancer.js/tree/audioapi/examples/aurora

I'll try setting it up as a gh-page later.
