### ISSUE TITLE
Can I use this to get the beats of an existing audio source?

### ISSUE THREAD

**Issue by comster** [jsantell/dancer.js#13]
I'm about to take a deeper look at how this might be possible, specifically in use with aurora.js.

Just thought I'd ask to see if you have any guidance.  Thanks for the great lib!

**Comment by jsantell** [comment]
The next phase for dancer.js is essentially latching on to any arbitrary Audio element. Aurora uses an Audio object, so it's possible that this could be exposed (not sure if it is currently, will have to dig), and once exposed, the new interface changes to dancer should allow you to read audio data from an aurora-transcoded audio file.

Trying to tackle implementing [this node](http://chromium.googlecode.com/svn-history/r2003/trunk/samples/audio/specification/specification.html#MediaElementAudioSourceNode-section) in webkit -- I'll push this to a branch soon (tomorrow, most likely), if you'd like to see the current state

**Comment by comster** [comment]
Thanks for the follow up.  I'll be watching and helping if I can.  Aurora does expose the underlying components, but I'm still not 100% on how it's all put together and they seem to be in dev too.

But having dancer work with any audio/local file source would be terrific!
