### ISSUE TITLE
Function to update beats frequency and threshold on-the-fly

### ISSUE THREAD

**Issue by Yahav** [jsantell/dancer.js#16]
beat.js Line 19:  
SEARCH FOR: "Beat.prototype = {"
ADD AFTER: 
    setparam  : function (frequency,threshold) { 
    this.frequency = frequency || options.frequency || [ 0, 10]; // 0, 10
    this.threshold = threshold || options.threshold || 0.3; // 0.3
      return this;
    },

**Comment by cesutherland** [comment]
Even better would be:
settings : function (options) {
  // handle frequency, threshold
},

**Comment by jsantell** [comment]
Word, I'll add this as well as the renaming of `beat` to `kick`. Thanks!
