### ISSUE TITLE
Changing audio volume doesn't seem to work

### ISSUE THREAD

**Issue by Yahav** [jsantell/dancer.js#21]
using Webkit to test it.
i'm trying to change the volume of the audio:
dancer.audioAdapter.audio.volume=0.1
OR
dancer.audio.volume=0

doesn't seem to work.

a function to control the volume would be great.

**Comment by jsantell** [comment]
Looks like you can't use the audio source on WebKit to change the volume like you can in Firefox.. has to be done with a GainNode. Will look into it

**Comment by jsantell** [comment]
Added `setVolume()` and `getVolume()` in b96bb998f1de0a577be626226ab999ee1f685b3a -- future additions could possibly bind the volumechange event for the audio element in WebKit to change the gainNode in the webkit implemetnation
