### ISSUE TITLE
Insecure Operation in FF14

### ISSUE THREAD

**Issue by jsantell** [jsantell/dancer.js#22]
Get the following message in Firefox 14:
SecurityError: The operation is insecure.
this.signal[ i ] = ( e.frameBuffer[ 2 \* i ] + e.frameBuffer[ 2 \* i + 1 ] ) / 2;
adapterMoz.js, line 69

**Comment by jsantell** [comment]
Not happening anymore in FF14 OSX?

**Comment by shoofle** [comment]
This is happening for me in FF20, Ubuntu 12.10.

**Comment by gdipkf1986** [comment]
FF22 still got this problme when the audio element src is local data
