### ISSUE TITLE
Add support for livestream (eg: shoutcast, ogg livestream, etc)

### ISSUE THREAD

**Issue by dimassony** [jsantell/dancer.js#30]

**Comment by Yahav** [comment]
Live streams actually supported.
i've tested it under Chrome and Firefox(using flash), with Icecast mp3 streams and it works.

**Comment by jsantell** [comment]
You're using v0.2.x, correct? When webkit uses XHR and pulls down a buffer, not the later versions which use an audio source? Post up a demo page of it if you can and I'll rework the XHR back into the current version for streams

**Comment by Yahav** [comment]
This has been fixed, probably in the last version of Chrome. anyway it now work for me even with live Shoutcast/Icecast streams, cheers. (not the xhr version)

**Comment by jsantell** [comment]
Excellent! Good to hear, and would love to see a link of in action!
