### ISSUE TITLE
Music is playing but no kicks in Chrome.

### ISSUE THREAD

**Issue by Yahav** [jsantell/dancer.js#31]
the official example (http://jsantell.github.com/dancer.js/) doesn't work in chrome in my workplace and laptop, how every it does work on my personal PC at home.
the music is playing but no kicks.

**Comment by Yahav** [comment]
- the FFT spectrum is blank while playing the music.

**Comment by jsantell** [comment]
I remember you showing me this before -- do other [Web Audio demos](http://chromium.googlecode.com/svn/trunk/samples/audio/index.html) work? Which chrome versions?

**Comment by jsantell** [comment]
Or same machines as in #23?
- HOME PC: (Win7,Chrome‪21.0.1180.75 m‬) : playing music and beating.
- WORK PC: (Win7,Chrome‪21.0.1180.75 m): playing music but not beating (no errors in console) - this.proc.onaudioprocess is never called.
- FRIEND PC: (Win7,Chrome‪21.0.1180.75 m): not playing music nor beating (no errors in console) - this.proc.onaudioprocess is never called as well.

**Comment by Yahav** [comment]
Same machines.

those demo's work
http://chromium.googlecode.com/svn/trunk/samples/audio/visualizer-gl.html
http://airtightinteractive.com/demos/js/reactive/
etc

This one doesn't work as well
http://www.storiesinflight.com/jsfft/visualizer_webaudio/

**Comment by Yahav** [comment]
@jsantell is there any proggress with this one?

**Comment by jsantell** [comment]
I haven't been able to recreate this on my windows machine in Windows 7, Chrome :[ planning a large rewrite so hopefully that fixes the issue..

**Comment by Yahav** [comment]
This has been fixed, probably in the last version of Chrome. anyway it now work for me even with live Shoutcast/Icecast streams, cheers.

**Comment by jsantell** [comment]
Awesome :+1:
