### ISSUE TITLE
Causes Chrome to crash

### ISSUE THREAD

**Issue by jsantell** [jsantell/dancer.js#5]
??? Happening occasionally in Chrome v18, need more info

Edit: Also crashes Chromium? http://news.ycombinator.com/item?id=4074884
Have not noticed crashing since Chrome v19

**Comment by Yahav** [comment]
it happen to me as well in the pc at work.
Chrome crash right after the song is loaded and ready to play.

**Comment by jsantell** [comment]
Closing, more info in #23, will also add Chromium to test list -- thanks!
